# Generated by Django 3.2.4 on 2021-06-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRetaguarda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaristas',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
